---
- hosts: localhost
  vars:
    www_www_source_path: /var/www
    config_path: /tmp/ighestates-master/gcp/config
    node_install_path: /usr/local/lib/node_modules
  environment:
    NODE_PATH: "{{ node_install_path }}"
  tasks:
    - name: install node and npm
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
        - nginx

    - name: install npm packages
      npm:
        name: "{{ item }}"
        global: yes
        state: present
        path: "{{ config_path }}"
      loop:
        - pm2
        - express

#    - name: install express
#      become: true
#      shell: npm install -g express
#      args:
#        chdir: "{{ config_path }}"

    - name: make {{ www_source_path }} directory
      become: true
      file:
        path: "{{ www_source_path }}"
        state: directory

    - name: copy source to /var/www
      become: true
      copy:
        src: /tmp/ighestates-master/dist/ighestates
        dest: "{{ www_source_path }}"

    - name: update pm2 processor file
      replace:
        path:
        regexp: '"NODE_PATH": "..."'
        replace: '"NODE_PATH": "{{ node_install_path }}"'

    - name: start pm2
      shell: pm2 start pm2_processor.json
      args:
        chdir: "{{ config_path }}"
