---
- hosts: localhost
  vars:
    source_path: /var/www
    config_path: /tmp/ighestates-master/gcp/config
  tasks:
    - name: install node and npm
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
        - nginx

    - name: install npm packages
      npm:
        name: "{{ item }}"
        global: yes
        state: present
        path: "{{ config_path }}"
      loop:
        - pm2

    - name: install express
      become: true
      shell: npm install -g express
      args:
        chdir: "{{ config_path }}"

    - name: make {{ source_path }} directory
      become: true
      file:
        path: "{{ source_path }}"
        state: directory

    - name: copy source to /var/www
      become: true
      copy:
        src: /tmp/ighestates-master/dist/ighestates
        dest: "{{ source_path }}"

    - name: start pm2
      shell: pm2 start {{ config_path }}/server.js --name ighestates
