---
- hosts: localhost
  become: true
  environment:
    ANSIBLE_CALLBACK_WHITELIST: profile_tasks
  tasks:

    - name: get node package
      unarchive:
        src: https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz
        dest: /opt
        remote_src: yes
        owner: root
        group: root
        mode: 0755

    - name: create links for node bin directory
      file:
        src: /opt/node-v12.18.3-linux-x64/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        state: link
      loop:
        - node
        - npm
        - npx

#    - name: install angular
#      npm:
#        name: '@angular/cli'
#        state: present
#        global: yes
#        path: /usr/local/bin/
#        executable: /usr/local/bin/

    - name: install angular
      shell: 'npm install -g @angular/cli'

    - name: build and deploy app
      shell:
        cmd: "{{ item }}"
        args:
          chdir: /tmp/ighestates-master/
      loop:
        - "ng build --prod"
        - "ng update @angular/cli @angular/core"
        - "ng add ngx-deploy-npm"
        - "ng deploy ighestates"

