---
- hosts: localhost
  become: true
  tasks:

    - name: get node package
      unarchive:
        src: https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz
        dest: /opt
        remote_src: yes
        owner: root
        group: root
        mode: 0755

    - name: create links for node bin directory
      file:
        src: /opt/node-v12.18.3-linux-x64/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        state: link
      loop:
        - node
        - npm
        - npx

    - name: install angular
      npm:
        name: '@angular/cli'
        state: present
        global: yes

    - name: create links for angular
      file:
        src: /opt/node-v12.18.3-linux-x64/lib/node_modules/@angular/cli/bin/ng
        dest: /usr/local/bin/ng
        state: link

    - name: build and deploy app
      shell:
        cmd: "{{ item }}"
        args:
          chdir: /tmp/ighestates-master/
      loop:
        - "ng update @angular/cli @angular/core"
        #- "ng build --prod"
        - "ng add ngx-deploy-npm"
        - "ng deploy ighestates"

