---
- hosts: localhost
  tasks:

    - name: get node package
      unarchive:
        src: https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz
        dest: /opt/node/
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: set node permissions
      file:
        path: /opt/node/
        owner: bigg74
        group: bigg74
        recurse: yes

    - name: create links for node bin directory
      file:
        src: /opt/node/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        mode: 0755
        owner: bigg74
        group: bigg74
        state: link
      loop:
        - node
        - npm
        - npx

    - name: install angular
      npm:
        name: '@angular/cli'
        state: present
        global: yes

    - name: create links for angular
      file:
        src: /opt/node/lib/node_modules/@angular/cli/bin/ng
        dest: /usr/local/bin/ng
        mode: 0755
        owner: bigg74
        group: bigg74
        state: link

    - name: build and deploy app
      shell:
        cmd: "{{ item }}"
        chdir: /tmp/ighestates-master/
      loop:
        #- "ng update @angular/cli @angular/core"
        #- "ng build --prod"
        - "ng add ngx-deploy-npm"
        - "ng deploy ighestates"

