---
- hosts: localhost
  vars:
    www_source_path: /var/www
    config_path: /tmp/ighestates-master/gcp/config
    node_install_path: "{{ www_source_path }}/ighestates/node_modules"
    pm2_file: "{{ config_path }}/pm2_processor.json"

  tasks:
    - name: install apt packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
        - nginx
      register: result
      retries: 10
      delay: 60
      until: result is not failed

    - name: make {{ www_source_path }} directory
      become: true
      file:
        path: "{{ www_source_path }}"
        state: directory

    - name: copy source to /var/www
      become: true
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: '/tmp/ighestates-master/dist/ighestates', dest: "{{ www_source_path }}"}
        - {src: "{{ config_path }}/package.json", dest: "{{ www_source_path }}/ighestates/"}

    - name: install npm packages
      become: ture
      shell: npm install pm2 -g {{ www_source_path }}/ighestates/
      register: result
      retries: 10
      delay: 60
      until: result is not failed

    - name: update pm2 processor file
      replace:
        path: "{{ pm2_file }}"
        regexp: '"NODE_PATH": "..."'
        replace: '"NODE_PATH": "{{ node_install_path }}"'

    - name: start pm2
      shell: pm2 start {{ pm2_file }}
      args:
        chdir: "{{ config_path }}"

    - name: copy nginx server conf
      become: true
      copy:
        src: "{{ config_path }}/server.conf"
        dest: /etc/nginx/conf.d/server.conf

    - name: restart nginx
      become: true
      service:
        name: nginx
        state: restarted
