---
- hosts: localhost
  become: true
  tasks:
    - name: install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm

    - name: install ansible
      npm:
        name: '@angular/cli'
        global: yes


